// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/_layout.tsx";
import * as $3 from "./routes/_middleware.ts";
import * as $4 from "./routes/api/products/[productId].tsx";
import * as $5 from "./routes/api/products/index.ts";
import * as $6 from "./routes/api/test.tsx";
import * as $7 from "./routes/index.tsx";
import * as $8 from "./routes/products/[id].tsx";
import * as $$0 from "./islands/Carousel.tsx";
import * as $$1 from "./islands/Countdown.tsx";
import * as $$2 from "./islands/Deciding.tsx";
import * as $$3 from "./islands/Pagination.tsx";
import * as $$4 from "./islands/SearchForm.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/_layout.tsx": $2,
    "./routes/_middleware.ts": $3,
    "./routes/api/products/[productId].tsx": $4,
    "./routes/api/products/index.ts": $5,
    "./routes/api/test.tsx": $6,
    "./routes/index.tsx": $7,
    "./routes/products/[id].tsx": $8,
  },
  islands: {
    "./islands/Carousel.tsx": $$0,
    "./islands/Countdown.tsx": $$1,
    "./islands/Deciding.tsx": $$2,
    "./islands/Pagination.tsx": $$3,
    "./islands/SearchForm.tsx": $$4,
  },
  baseUrl: import.meta.url,
};

export default manifest;
