import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import Breadcrumb from "./components/Breadcrumb";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  console.log("Root layout executed");
  return (
    <html lang="en">
      <body className={inter.className}>
        <Breadcrumb />
        <div className="flex gap-4">
          <Link href={"/about"}>About</Link>
          <Link href={"/"}>Home</Link>
        </div>

        {children}
      </body>
    </html>
  );
}
